namespace Cirreum.Authorization.Configuration;

using Cirreum.AuthorizationProvider.Configuration;

public class EntraAuthorizationSettings
	: AuthorizationProviderSettings<EntraAuthorizationInstanceSettings>;